language: python
python:
  - "2.7"

install:
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
  - pip install -r requirements.txt

script:
  - pytest
